name: Lint Python and Dockerfile

on:
  push:
    paths:
      - '**.py'
      - 'Dockerfile'
  pull_request:
    paths:
      - '**.py'
      - 'Dockerfile'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ############################
      # Python Linting with Ruff #
      ############################
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff (fail only on errors)
        run: |
          ruff . --select E --output-format=github

      ##################################
      # Dockerfile Linting with Hadolint #
      ##################################
      - name: Install hadolint
        run: |
          wget -qO /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /bin/hadolint

      - name: Lint Dockerfile (fail on severity >= 4)
        run: |
          if [ -f Dockerfile ]; then
            hadolint Dockerfile --format json | tee lint-results.json
            python3 <<EOF
            import json
            with open('lint-results.json') as f:
               issues = json.load(f)
               high = [i for i in issues if i['severity'] >= 4]
               print(f'Found {len(high)} high-severity Dockerfile issue(s).')
               exit(1) if high else exit(0)
          EOF
          else
            echo 'No Dockerfile found, skipping hadolint.'
          fi
      #########################
      # Python Unit Tests     #
      #########################
      - name: Run Unit Tests with pytest
        run: |
          pytest tests

      ##################################
